name: CI

on:
  push:
  pull_request:

permissions:
  contents: "read"

jobs:
  ci:
    name: CI
    runs-on: "ubuntu-latest"
    container:
      image: "archlinux:base-devel"
      options: --security-opt seccomp=unconfined  # required for unshare

    steps:
      - run: "pacman-key --init"
      - run: "pacman -Syu --noconfirm --noprogressbar"
      - uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1"
      - uses: "actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e"
        with:
          go-version: "stable"
          check-latest: true
      - run: "go mod download"
      - parallel:
          - run: 'find . -mindepth 1 -name ".*" -prune -o -type f -name "*.go" -exec gofmt -d {} +'
          - run: "go fix -diff ./..."
          - run: "go vet ./..."
          - run: "go test ./..."
          - run: |
              go build -o "${RUNNER_TEMP}/alpmtest" ./internal/alpmtest
              setpriv --reuid=1000 --regid=1000 --clear-groups --inh-caps=-all --ambient-caps=-all -- "${RUNNER_TEMP}/alpmtest"  # run as a regular user since makepkg rejects root
          - run: |
              go build -o "${RUNNER_TEMP}/pacorphan" .
              go build -o "${RUNNER_TEMP}/pacorphantest" ./internal/pacorphantest
              setpriv --reuid=1000 --regid=1000 --clear-groups --inh-caps=-all --ambient-caps=-all -- "${RUNNER_TEMP}/pacorphantest" --cmd "${RUNNER_TEMP}/pacorphan"  # run as a regular user since makepkg rejects root
